// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCetD32AqgDgcfDkbiIOtMGsJRmEAlQjSQ',
    appId: '1:891906427008:web:dba7dfc7b240d3d75bbe65',
    messagingSenderId: '891906427008',
    projectId: 'flashcards-app-7eadf',
    authDomain: 'flashcards-app-7eadf.firebaseapp.com',
    storageBucket: 'flashcards-app-7eadf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU25hpP32gsXi5qfJUiRrmxYmcTbY_ijc',
    appId: '1:891906427008:android:7672de3ce39e8ff45bbe65',
    messagingSenderId: '891906427008',
    projectId: 'flashcards-app-7eadf',
    storageBucket: 'flashcards-app-7eadf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPR421cUbvgTPMjGJRSgxpsam9lV-4bYc',
    appId: '1:891906427008:ios:7d15397910cbb49a5bbe65',
    messagingSenderId: '891906427008',
    projectId: 'flashcards-app-7eadf',
    storageBucket: 'flashcards-app-7eadf.appspot.com',
    iosClientId: '891906427008-frk1ti37euhgb6sgdld5diuhdhc5e5um.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashcardsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPR421cUbvgTPMjGJRSgxpsam9lV-4bYc',
    appId: '1:891906427008:ios:7d15397910cbb49a5bbe65',
    messagingSenderId: '891906427008',
    projectId: 'flashcards-app-7eadf',
    storageBucket: 'flashcards-app-7eadf.appspot.com',
    iosClientId: '891906427008-frk1ti37euhgb6sgdld5diuhdhc5e5um.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashcardsApp',
  );
}
